services:
  - type: web
    name: justdothething-frontend
    env: static
    buildCommand: yarn build:website
    staticPublishPath: ./frontend/packages/website/dist
    envVars:
      - key: VITE_NODE_ENV
        value: production
      - key: VITE_API_URL_PROD
        value: https://justdothething.onrender.com/api
      - key: VITE_FRONTEND_URL_PROD
        value: https://justdothething-website-s4fb.vercel.app
          
  - type: web
    name: justdothething-backend
    env: node
    buildCommand: cd backend && npm ci && npx prisma generate && npm run build
    startCommand: cd backend && npm run start
    healthCheckPath: /api/health
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://justdothething-website-s4fb.vercel.app
      - key: FRONTEND_URL_PROD
        value: https://justdothething-website-s4fb.vercel.app
      - key: BACKEND_URL_PROD
        value: https://justdothething.onrender.com
      - key: CORS_ORIGINS
        value: https://justdothething-website-s4fb.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false